In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
df1 = pd.read_csv("dataset/page1.csv")
df2 = pd.read_csv("dataset/page2.csv")
df3 = pd.read_csv("dataset/page3.csv")
df4 = pd.read_csv("dataset/page1_2.csv")
df5 = pd.read_csv("dataset/page2_1.csv")
df6 = pd.read_csv("dataset/page2_2.csv")
df7 = pd.read_csv("dataset/page3_1.csv")
df8 = pd.read_csv("dataset/page3_2.csv")

In [6]:
df = pd.concat([df1,df2,df3,df4,df5,df6,df7,df8])

In [7]:
df.shape

(240, 9)

In [8]:
df.isnull().sum()

title            124
address          124
total_ratings    124
rating           124
type             124
type2            126
description      126
timing           165
phone            124
dtype: int64

In [9]:
df.dropna(inplace=True)

In [10]:
df.shape

(73, 9)

In [11]:
df.duplicated().sum()

29

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df.shape

(44, 9)

In [185]:
df.columns

Index(['title', 'address', 'total_ratings', 'rating', 'type', 'type2',
       'description', 'timing', 'phone'],
      dtype='object')

In [186]:
combined_cols = df['address'] + " " +df['type'] + " " + df['type2'] + " " + df['description']
combined_cols

0     R C Dutt Road Alkapuri, Vadodara 390007 India ...
2     Jetalpur Rd First Floor, Tapan Complex ,Next T...
5     R C Dutt Road 3rd Floor, Shreem Shalini Mall, ...
8     Akota Garden, Akota The Gateway Hotel, Vadodar...
9     Opposite Parsi Agiary Surya Palace Hotel, Vado...
13    Sama Savli Rd Spenta Complex, 101/102, 1st Flo...
14    18/19, Alkapuri Society, Near Rbs Bank Lane Op...
20    Yash Kamal Building, Sayajiganj Rd Opposite M....
23    Inorbit Mall, Astoriya Complex, 1st Floor, Nea...
27    56 Old Padra Road Diwalipura, Vadodara 390007 ...
28    R C Dutt Road Near Standard Chartered Bank, Je...
9     Rocv. Akota Mujhmahuda, Vadodara 390020 India ...
12    Shop No. 4/3 & 4/4, Govardhan Apartments Near ...
15    101/102 Race Course Road Opposite Axis Bank, A...
17    Meraki Kitchen Nf-39, First Floor,india Bull M...
23    4, Rajnagar Society, G.E.B. Road Opposite Ajit...
24    Shantanam Beside Tbz 1st Floor Race Course Roa...
25    Ellora Park Shaimi Society, Vadodara 39002

In [187]:
from sklearn.feature_extraction.text import TfidfVectorizer
vector = TfidfVectorizer()
vector_combined_cols = vector.fit_transform(combined_cols)

In [188]:
print(vector_combined_cols)

  (0, 76)	0.228257118981397
  (0, 82)	0.2408496571923109
  (0, 85)	0.3457130594480065
  (0, 137)	0.3083013428145907
  (0, 197)	0.15415067140729535
  (0, 77)	0.1279438929698761
  (0, 198)	0.1279438929698761
  (0, 87)	0.3457130594480065
  (0, 94)	0.1326963644577797
  (0, 4)	0.3457130594480065
  (0, 0)	0.29109915728001184
  (0, 93)	0.10691300441305444
  (0, 13)	0.18101945198715613
  (0, 194)	0.11483611036696782
  (0, 28)	0.2716066118739048
  (0, 155)	0.21699270970591017
  (0, 63)	0.3149561047664126
  (1, 32)	0.12781552876431432
  (1, 111)	0.24136769805097422
  (1, 113)	0.32259500004644864
  (1, 190)	0.32259500004644864
  (1, 126)	0.32259500004644864
  (1, 54)	0.2252052644053815
  (1, 185)	0.32259500004644864
  (1, 73)	0.18926161067272218
  :	:
  (25, 130)	0.29861225713366674
  (25, 51)	0.23460225527376202
  (25, 32)	0.1331488026547216
  (25, 137)	0.1331488026547216
  (25, 197)	0.1331488026547216
  (25, 77)	0.1105125005321036
  (25, 198)	0.1105125005321036
  (25, 94)	0.11461748354961589
  

In [189]:
from sklearn.metrics.pairwise import cosine_similarity
similarity  = cosine_similarity(vector_combined_cols)
np.set_printoptions(threshold=10)
print(similarity)

[[1.         0.27914109 0.50647798 ... 0.07830509 0.11493614 0.08885309]
 [0.27914109 1.         0.27843334 ... 0.1407861  0.1123189  0.03259369]
 [0.50647798 0.27843334 1.         ... 0.21159174 0.09147787 0.05262242]
 ...
 [0.07830509 0.1407861  0.21159174 ... 1.         0.03878514 0.15976993]
 [0.11493614 0.1123189  0.09147787 ... 0.03878514 1.         0.0246987 ]
 [0.08885309 0.03259369 0.05262242 ... 0.15976993 0.0246987  1.        ]]


In [190]:
similarity.shape 

(27, 27)

In [191]:
titles = df['title'].tolist()
titles

['Peshawri',
 '22nd Parallel',
 'The Barbeque Nation',
 'Kai Asia',
 'Azure',
 'Sankalp Restaurant',
 'Fiorella Italian Restaurant',
 'Havmor Restaurant',
 'Mirch Masala Restaurant',
 'Havmor Restaurant',
 'Chung Faa',
 'PinXX - KIitchen and Lounge',
 'Subway',
 'Sankalp Restaurant',
 'Meraki',
 'White Potato Restaurant',
 'La Benito',
 "Gusto's Pizzeria",
 'Cafe Fitoor',
 'Hotel Nyay Mandir Restaurant',
 'Sankalp Restaurant',
 'Curry Kingdom Vadodara',
 'Khamma Ghani - The Royal Kitchens Of Rajasthan',
 'The Dhaba',
 'Barbeque Nation',
 'Ekta Restaurant & Banquet',
 '22nd Parallel']

In [192]:
import difflib
user_input = input("enter the restaurant name :")
restau_name = difflib.get_close_matches(user_input,titles)
print(restau_name)

['22nd Parallel', '22nd Parallel']


In [193]:
close_match = restau_name[0]
print(close_match) 

22nd Parallel


In [194]:
df['index'] = range(len(df))

In [195]:
index_of_the_movie = df[df['title']==close_match]['index'].values[0]

In [196]:
index_of_the_movie

1

In [197]:
similarity_score = list(enumerate(similarity[index_of_the_movie]))
print(similarity_score)

[(0, 0.2791410887622738), (1, 1.0000000000000002), (2, 0.27843333917589164), (3, 0.08434577927321048), (4, 0.23505975113411912), (5, 0.3254230363063388), (6, 0.212541318247666), (7, 0.11598227137722861), (8, 0.30826979220250517), (9, 0.28298167871320523), (10, 0.1103804476337974), (11, 0.13914570271660034), (12, 0.0792421198824297), (13, 0.17173561386872596), (14, 0.27005965623826944), (15, 0.12331544122959738), (16, 0.12738821576591475), (17, 0.016749664955108882), (18, 0.14328185949939373), (19, 0.1132229314161492), (20, 0.12892920151926213), (21, 0.07270741350871898), (22, 0.17893639756137653), (23, 0.08518562564795308), (24, 0.14078610223627447), (25, 0.11231890340797793), (26, 0.03259369430523112)]


In [198]:
sorted_similar_restaurants = sorted(similarity_score, key = lambda x:x[1], reverse = True) 
print(sorted_similar_restaurants)

[(1, 1.0000000000000002), (5, 0.3254230363063388), (8, 0.30826979220250517), (9, 0.28298167871320523), (0, 0.2791410887622738), (2, 0.27843333917589164), (14, 0.27005965623826944), (4, 0.23505975113411912), (6, 0.212541318247666), (22, 0.17893639756137653), (13, 0.17173561386872596), (18, 0.14328185949939373), (24, 0.14078610223627447), (11, 0.13914570271660034), (20, 0.12892920151926213), (16, 0.12738821576591475), (15, 0.12331544122959738), (7, 0.11598227137722861), (19, 0.1132229314161492), (25, 0.11231890340797793), (10, 0.1103804476337974), (23, 0.08518562564795308), (3, 0.08434577927321048), (12, 0.0792421198824297), (21, 0.07270741350871898), (26, 0.03259369430523112), (17, 0.016749664955108882)]


In [199]:
i = 1
for r in sorted_similar_restaurants:
  if i==6:
    break;
  index = r[0]
  title_from_index = df[df['index']==index]['title'].values[0]
  print(i, '.',title_from_index)
  i+=1

1 . 22nd Parallel
2 . Sankalp Restaurant
3 . Mirch Masala Restaurant
4 . Havmor Restaurant
5 . Peshawri
